# exceptions.py
class TempoEccessivoError(Exception):
    """Custom exception to handle timeout situations."""
    pass
